"""empty message

Revision ID: 993ea9885c47
Revises: 586c5d121d24
Create Date: 2021-05-30 13:22:59.108577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993ea9885c47'
down_revision = '586c5d121d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
